USE [master]
GO
/****** Object:  Database [Proyecto_Taller_2]    Script Date: 13/11/2024 11:38:25 ******/
CREATE DATABASE [Proyecto_Taller_2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Proyecto_Taller_2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Proyecto_Taller_2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Proyecto_Taller_2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Proyecto_Taller_2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Proyecto_Taller_2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Proyecto_Taller_2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Proyecto_Taller_2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Proyecto_Taller_2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Proyecto_Taller_2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Proyecto_Taller_2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Proyecto_Taller_2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Proyecto_Taller_2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Proyecto_Taller_2] SET  MULTI_USER 
GO
ALTER DATABASE [Proyecto_Taller_2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Proyecto_Taller_2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Proyecto_Taller_2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Proyecto_Taller_2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Proyecto_Taller_2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Proyecto_Taller_2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Proyecto_Taller_2] SET QUERY_STORE = ON
GO
ALTER DATABASE [Proyecto_Taller_2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Proyecto_Taller_2]
GO
/****** Object:  Table [dbo].[CATEGORIA]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIA](
	[id_categoria] [int] IDENTITY(1,1) NOT NULL,
	[nombre_categoria] [varchar](100) NOT NULL,
	[descripcion_categoria] [varchar](200) NULL,
	[estado_categoria] [int] NOT NULL,
 CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[id_categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[id_cliente] [int] IDENTITY(1,1) NOT NULL,
	[id_persona] [int] NOT NULL,
	[id_nivel] [int] NOT NULL,
	[observaciones] [varchar](200) NULL,
	[monto_total] [float] NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[id_cliente] ASC,
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOCALIDAD]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCALIDAD](
	[id_localidad] [int] IDENTITY(1,1) NOT NULL,
	[nombre_localidad] [varchar](100) NOT NULL,
	[id_provincia] [int] NOT NULL,
 CONSTRAINT [PK_LOCALIDAD] PRIMARY KEY CLUSTERED 
(
	[id_localidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[METODO_PAGO]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[METODO_PAGO](
	[id_metodo] [int] IDENTITY(1,1) NOT NULL,
	[nombre_metodo] [varchar](100) NOT NULL,
	[descripcion_metodo] [varchar](200) NOT NULL,
 CONSTRAINT [PK_METODO_PAGO] PRIMARY KEY CLUSTERED 
(
	[id_metodo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NIVEL]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NIVEL](
	[id_nivel] [int] IDENTITY(1,1) NOT NULL,
	[descuento] [int] NOT NULL,
	[nombre_nivel] [varchar](100) NULL,
	[estado_nivel] [int] NULL,
 CONSTRAINT [PK_NIVEL] PRIMARY KEY CLUSTERED 
(
	[id_nivel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[id_persona] [int] IDENTITY(1,1) NOT NULL,
	[nombre_persona] [varchar](100) NOT NULL,
	[apellido_persona] [varchar](100) NOT NULL,
	[dni] [int] NOT NULL,
	[email_persona] [varchar](100) NOT NULL,
	[direccion_persona] [varchar](200) NOT NULL,
	[id_localidad] [int] NOT NULL,
	[fecha_nacimiento] [date] NOT NULL,
 CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[id_producto] [int] IDENTITY(1,1) NOT NULL,
	[nombre_producto] [varchar](100) NOT NULL,
	[precio_producto] [float] NOT NULL,
	[descripcion_producto] [varchar](200) NULL,
	[stock_producto] [int] NOT NULL,
	[baja_producto] [int] NOT NULL,
	[id_categoria] [int] NOT NULL,
	[ruta_imagen] [varchar](255) NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROVINCIA]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVINCIA](
	[id_provincia] [int] IDENTITY(1,1) NOT NULL,
	[nombre_provincia] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PROVINCIA] PRIMARY KEY CLUSTERED 
(
	[id_provincia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROL]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL](
	[id_rol] [int] IDENTITY(1,1) NOT NULL,
	[nombre_rol] [varchar](100) NOT NULL,
	[descripcion_rol] [varchar](200) NOT NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[id_rol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[usuario] [varchar](100) NOT NULL,
	[pass] [varchar](100) NOT NULL,
	[baja_usuario] [int] NOT NULL,
	[id_persona] [int] NOT NULL,
	[id_rol] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC,
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENTA_CABECERA]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENTA_CABECERA](
	[id_venta] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NOT NULL,
	[precio_total] [float] NOT NULL,
	[id_metodo] [int] NOT NULL,
	[id_usuario] [int] NOT NULL,
 CONSTRAINT [PK_VENTA_CABECERA] PRIMARY KEY CLUSTERED 
(
	[id_venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENTA_DETALLE]    Script Date: 13/11/2024 11:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENTA_DETALLE](
	[cantidad] [int] IDENTITY(1,1) NOT NULL,
	[precio_subtotal] [float] NOT NULL,
	[id_producto] [int] NOT NULL,
	[id_venta] [int] NOT NULL,
 CONSTRAINT [PK_VENTA_DETALLE] PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC,
	[id_venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD  CONSTRAINT [DF_estado_categoria]  DEFAULT ((1)) FOR [estado_categoria]
GO
ALTER TABLE [dbo].[NIVEL] ADD  CONSTRAINT [DF_estado_nivel]  DEFAULT ((1)) FOR [estado_nivel]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD  CONSTRAINT [DF_baja_producto]  DEFAULT ((0)) FOR [baja_producto]
GO
ALTER TABLE [dbo].[USUARIO] ADD  CONSTRAINT [DF_baja_usuario]  DEFAULT ((1)) FOR [baja_usuario]
GO
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_NIVEL] FOREIGN KEY([id_nivel])
REFERENCES [dbo].[NIVEL] ([id_nivel])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_NIVEL]
GO
ALTER TABLE [dbo].[LOCALIDAD]  WITH CHECK ADD  CONSTRAINT [FK_LOCALIDAD_PROVINCIA] FOREIGN KEY([id_provincia])
REFERENCES [dbo].[PROVINCIA] ([id_provincia])
GO
ALTER TABLE [dbo].[LOCALIDAD] CHECK CONSTRAINT [FK_LOCALIDAD_PROVINCIA]
GO
ALTER TABLE [dbo].[PERSONA]  WITH CHECK ADD  CONSTRAINT [FK_PERSONA_LOCALIDAD] FOREIGN KEY([id_localidad])
REFERENCES [dbo].[LOCALIDAD] ([id_localidad])
GO
ALTER TABLE [dbo].[PERSONA] CHECK CONSTRAINT [FK_PERSONA_LOCALIDAD]
GO
ALTER TABLE [dbo].[PRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTO_CATEGORIA] FOREIGN KEY([id_categoria])
REFERENCES [dbo].[CATEGORIA] ([id_categoria])
GO
ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [FK_PRODUCTO_CATEGORIA]
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_ROL] FOREIGN KEY([id_rol])
REFERENCES [dbo].[ROL] ([id_rol])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_ROL]
GO
ALTER TABLE [dbo].[VENTA_CABECERA]  WITH CHECK ADD  CONSTRAINT [FK_VENTA_CABECERA_METODO_PAGO] FOREIGN KEY([id_metodo])
REFERENCES [dbo].[METODO_PAGO] ([id_metodo])
GO
ALTER TABLE [dbo].[VENTA_CABECERA] CHECK CONSTRAINT [FK_VENTA_CABECERA_METODO_PAGO]
GO
ALTER TABLE [dbo].[VENTA_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_VENTA_DETALLE_PRODUCTO] FOREIGN KEY([id_producto])
REFERENCES [dbo].[PRODUCTO] ([id_producto])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] CHECK CONSTRAINT [FK_VENTA_DETALLE_PRODUCTO]
GO
ALTER TABLE [dbo].[VENTA_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_VENTA_DETALLE_VENTA_CABECERA] FOREIGN KEY([id_venta])
REFERENCES [dbo].[VENTA_CABECERA] ([id_venta])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] CHECK CONSTRAINT [FK_VENTA_DETALLE_VENTA_CABECERA]
GO
USE [master]
GO
ALTER DATABASE [Proyecto_Taller_2] SET  READ_WRITE 
GO
